name = "Raspberry Flavoured"
author = "raspmary"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a322c8660d20677109859ed290c509ce27ce05677c86905f8904c63f1db7dfa"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
