name = "Raspberry Flavoured"
author = "raspmary"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1768d2e65a472454ed96fb4429d2391268d90448157d436de8ecc87c20c681a0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
