name = "Raspberry Flavoured"
author = "raspmary"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "802a48d08c11d23c7f026fa756d6e45fb93fd101b8e1e39e9cdae92389d4cee8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
