name = "Raspberry Flavoured"
author = "raspmary"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d912f68bc853c2bab3829429602b88f5f7587ccdfb0134c2f4c0bbbb93968fdb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
