name = "Raspberry Flavoured"
author = "raspmary"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed8d2db67f963b5ed829733eabf12315ac06659df672fc0df06b322d5de3c329"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
