name = "Raspberry Flavoured"
author = "raspmary"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f888d3d929f489e7ea1d783d8a466ebd4ea834d3f518eb98def38d63ee3c6f1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
