name = "Raspberry Flavoured"
author = "raspmary"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d54fa3bff9da2a4e251646653dd39659b957125cb427d4c0e2788afffd9e04f8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
